[package]
name = "tauri-runtime-wry"
version = "0.2.1"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Wry bindings to the Tauri runtime"
edition = "2021"
rust-version = "1.56"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[dependencies]
#wry = { version = "0.12", default-features = false, features = [ "file-drop", "protocol" ] }
wry = { git = "https://github.com/tauri-apps/wry", rev = "27cf3735f717ffcc409e79031356ea0c99cadf8a", default-features = false, features = [ "file-drop", "protocol", "transparent", "fullscreen" ] }
tauri-runtime = { version = "0.2.1", path = "../tauri-runtime" }
tauri-utils = { version = "1.0.0-beta.3", path = "../tauri-utils" }
uuid = { version = "0.8.2", features = [ "v4" ] }
infer = "0.4"

####### egui
epi = { git = "https://github.com/wusyong/egui", branch = "tao" }
egui-tao = { git = "https://github.com/wusyong/egui", branch = "tao", features = ["epi"] }
egui_glow = { git = "https://github.com/wusyong/egui", branch = "tao" }
tao-glutin = { git = "https://github.com/wusyong/glutin", branch = "tao", version = "0.1.0"}
glow = "0.11"
once_cell = "1.8"

[target."cfg(windows)".dependencies]
ico = "0.1"
webview2-com = "0.7.0"

[target."cfg(windows)".dependencies.windows]
version = "0.25.0"
features = [
  "Win32_Foundation",
]

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
png = "0.16"
gtk = { version = "0.14", features = [ "v3_20" ] }

[features]
dox = [ "wry/dox" ]
system-tray = [ "wry/tray", "tauri-runtime/system-tray" ]
